### ISSUE TITLE
Фильтры

### ISSUE THREAD

**Issue by progzone122** [Semolik/AnimeVostPlayer#1]
Как сделать так, чтобы фильтры показывали все аниме в той или иной категории/жанре? А то как пробую, как ни крути возвращает массив из 50 объектов.
Пробовал в body запроса добавлять page, не помогает.

**Comment by Semolik** [comment]
Это ограничение api.

**Comment by progzone122** [comment]
А можно ли как-то обойти это ограничение? Очень при очень нужно.

**Comment by Semolik** [comment]
На сколько знаю нельзя. Напиши в телеграме скину файлик по документации но там мало что есть.
